title: "Corp Website — TryHackMe"
description: "Professional Corp Website lab documentation."

theme: jekyll-theme-primer

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - docs
